-- Superseded by scripts/import-dbpr.mjs.
--
-- This file used to hold an 11-record hand-verified sample of Pinellas
-- inspectors. Three of those eleven (HI405, HI16725, HI15804) no longer
-- appear in the DBPR extract at all, meaning their licenses are no longer
-- current — exactly the kind of record this site must never show. Rather
-- than maintain a hand-curated list that silently goes stale, the listings
-- table is now populated from the official DBPR public-records extract:
--
--   node scripts/import-dbpr.mjs --county pinellas
--
-- DBPR refreshes that extract weekly, so re-running the importer is what
-- keeps the directory honest.
